data_source postgres_db:
  type: postgres
  host: postgres
  port: 5432
  username: soda
  password: soda123
  database: postgres
  schema: public

soda_cloud:
  host: cloud.soda.io
  api_key_id: <key-id>
  api_key_secret: <secret>
